### ISSUE TITLE
Android: first execution error

### ISSUE THREAD

**Issue by kaiquewdev** [danielweinmann/TemAcucar#2]
[execution error](https://drive.google.com/file/d/0B-Yd5zfwO7tHRlVBTTlpQ2dYdzhzblpwdlNScjhwanJSSWhj/view?usp=sharing)

**Comment by kaiquewdev** [comment]
This documentation can supply these informations about installation?

https://facebook.github.io/react-native/docs/getting-started.html#content

**Comment by danielweinmann** [comment]
It should supply information about React Native installation. Not TemAcucar installation. The whole set of instructions are (in development) here: https://github.com/danielweinmann/TemAcucar/blob/master/README.md

Did you follow the whole steps on the README? If so, on which step did it break?

**Comment by danielweinmann** [comment]
Ha, by chance I ran into the same error message now and recognised the problem ;) you need to configure your app to connect to the local dev server via Wi-Fi: https://facebook.github.io/react-native/docs/running-on-device-android.html#configure-your-app-to-connect-to-the-local-dev-server-via-wi-fi
